const express = require("express");
const jwt = require("jsonwebtoken");
const User = require("../models/user");
const PasswordReset = require("../models/passwordReset");
const router = express.Router();
const crypto = require("crypto");
const userController = require("../controllers/user");
const upload = require("../middleware/fileUpload");
const SALT = process.env.PASSWORD_SALT;
const imageUpload = upload.single("image");
router.post("/register", imageUpload, userController.registerUser);
router.post("/login", userController.loginUser);
router.post("/password/reset-request", userController.resetRequest);
router.patch("/password", userController.patchPassword);
module.exports = router;
